;;;; regenerate.lisp - script for regenerating esejepg.pl static HTML from template files.

(ql:quickload "cl-emb")
(ql:quickload "cl-fad")
(ql:quickload "cl-ppcre")

;;; Stuff required for EMB templates.
(defparameter *configuration* '() "plist containing config parameters passed to EMB templates.")
(defparameter *essays* '() "plist containing essay descriptors generated by `defessay'.")
(defconstant +default-properties+ '(:title nil :url nil :orig-title nil :orig-url nil :date nil :orig-date nil :alt-translations nil :translators nil :editors nil :disabled nil :additional-html nil :part-of-hnp nil :description ""))

(defun make-environment ()
  (append (list :conf *configuration*) (list :essays *essays*)))

;;; Data processing code
;;; Used for being able to refer to essays declaratively.
(defun defessay (essay-id &rest properties)
  "Defines an essay by putting it's data into global *environment* variable, which will be an environment for
EMB templates. Please define essays from oldest to newest, to ensure proper order when iterating (from newest to
oldest."
  (push (append properties +default-properties+) *essays*)
  (push essay-id *essays*))

;;; Regeneration code

(defun template-to-generate-file-from-p (path)
  "Returns t if given file should generate a corresponding HTML in source."
  (not (or (search "templates/" (namestring path))
           (search "data/" (namestring path))
           (search "css/" (namestring path)))))

(defun sass-file-p (path)
  "Returns t if file has .scss extension (SASS stylesheet)."
  (ppcre:scan "\.scss$" (namestring path)))

(defun file-or-dir-to-delete-p (path)
  "Returns t if given file or directory should be deleted when cleaning."
  (let ((name (namestring path)))
    (not (or (search "img/" name)
             (search "js/" name)
             (ppcre:scan "humans.txt$" name)
             (ppcre:scan "site/$" name)))))

(defun make-group-template-path (pathname)
  "Used to select proper template based on directory processed HTML file is located in."
  (pathname (cl-ppcre:regex-replace "src/([A-Za-z]*)/.*" (namestring pathname) "src/templates/\\1\.html")))

(defun make-destination-path (pathname)
  "Where to put generated files."
  (pathname (cl-ppcre:regex-replace "src/" (namestring pathname) "site/")))

(defun process-template (pathname)
  "Run the template engine on selected HTML template, and return the processed code as string."
  (let ((content (cl-emb:execute-emb pathname
                                     :env (make-environment))))
    (cl-emb:execute-emb (make-group-template-path pathname)
                        :env (append (list :content content)
                                     (make-environment)))))

(defun save-file (content pathname)
  "Save content to file at `pathname', ensuring that all the required directories exist."
  (ensure-directories-exist pathname)
  (with-open-file (stream pathname :direction :output
                          :if-exists :overwrite
                          :if-does-not-exist :create)
    (format stream content)))

(defun generate-file (pathname)
  "Generate HTML from selected template."
  (save-file (process-template pathname)
             (make-destination-path pathname))
  (format t "Regenerated successfuly: ~A (from ~A)~%" (make-destination-path pathname) pathname))

(defun del-dir-or-file-noerror (pathname)
  "Delete file, don't crash on failure."
  (format t "Deleting: ~A~%" pathname)
  (ignore-errors (fad:delete-directory-and-files pathname)))

(defun delete-old-files ()
  "Delete all generated files."
  (ignore-errors
    (fad:walk-directory "site" 'del-dir-or-file-noerror :test 'file-or-dir-to-delete-p :if-does-not-exist :ignore :directories t)))

(defun make-css-file-name (name)
  "Generate path for generated CSS file."
  (cl-ppcre:regex-replace "src/"
                          (cl-ppcre:regex-replace "\.scss$"
                                                  name
                                                  ".css")
                          "site/"))

(defun generate-css (pathname)
  "Generate CSS file from SASS files."
  (let* ((name (namestring pathname))
         (css-name (make-css-file-name name))
         (command (format nil "/home/temporal/lib/sass/bin/sass --style expanded ~A:~A" name css-name)))
    (ensure-directories-exist css-name)
    (format t "Running command: ~A~%" command)
    #+LINUX(asdf:run-shell-command command)))


(defun generate-sitemap ()
  "Generate sitemap XML file for search engines."
  ;; TODO
)

(defun regenerate ()
  "Regenerate all static HTML from template files in src/ directory, and put them in site/ directory."
  (format t "Deleting old files...~%")
  (delete-old-files)

  (format t "Cleaning template environment...~%")
  (setf *essays* '())

  (format t "Loading essay data...~%")
  (load "src/data/essays.lisp")
  (format t "Loaded ~A essay descriptors.~%" (/ (length *essays*) 2))

  (format t "Regenerating static HTML files...~%")
  (fad:walk-directory "src" 'generate-file :test 'template-to-generate-file-from-p)

  (format t "Regenerating CSS files...~%")
  (fad:walk-directory "src/css" 'generate-css :test 'sass-file-p)

  (format t "Generating sitemap...~%")
  (generate-sitemap)

  (format t "Done!~%"))
